version: "3"
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    ports:
      - "2181:2181"
    networks:
      kafka-network:
        ipv4_address: 172.16.238.2

  kafka:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '9092'
      - '19092'
    environment:
      ZOOKEEPER: zookeeper:2181
      ADVERTISED_LISTENER: 172.20.10.3
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      kafka-network:
        ipv4_address: 172.16.238.3


  kafka-admin-boot:
    image: kafka-admin-boot
    ports:
      - '8080:8080'
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
    depends_on:
      - kafka
    networks:
      kafka-network:
        ipv4_address: 172.16.238.4

networks:
  kafka-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1